#!/bin/sh
# by Jochen Demmer
# Version 2.0 9th April 2015
# KLvmsnapshot

####
#### functions
####

red='\033[0;31m'
nocolor='\033[0m'
tellhow() {
	echo "usage: $0 <HOSTNAME> <LVMVG> <LVMPARTNAME> <LVMSSSIZE> <GUESTNAME>"
	echo "${red}All arguments are mandatory.${nocolor}"
	echo "HOSTNAME:\tThis corresponds to the name of the KVM guest in a short form, like srv003."
	echo "LVMVG:\t\tThis is the volume group where the logical volume belongs to, e.g. vg0."
	echo "LVMPARTNAME:\tThis is the name of the logical volume that needs to be saved, e.g. srv003_boot."
	echo "LVMSIZE:\tHow big the snapshot volume should be. Please choose reasonable size or backup may not work."
	echo "GUESTNAME:\tThis is the actual name of the kvm guest, e.g. srv003.my.domain."
}


####
#### modify corresponding to your needs
####

LVMSSPREFIX="snapsh_"		# prefix for snapshot volumes
VIRSHPATH="/usr/bin"		# path to where the virsh command is located
LVPATH="/sbin"			# path to where the lv commands are located
LOGTAG="dosnapshot"		# the tag that appears in syslog

####
#### no modifications down here
####

# Variables that are handed over
HOSTNAME=$1			# hostname e.g. srv003
LVMVG=$2			# VG name e.g. vg0
LVMPARTNAME=$3			# source partition name e.g. srv002_boot v srv007
LVMSSSIZE=$4			# Snapshot volume size e.g. 10G v 500M
GUESTNAME=$5			# name of the virt guest to give it virsh commands 

# assembled variables
LVMVOLDEV=/dev/$LVMVG/$LVMPARTNAME			# dev path of logical volume to backup
LVMSSDEV=/dev/$LVMVG/$LVMSSPREFIX$LVMPARTNAME		# dev path of logical volume snapshot device
LVMSSNAME=$LVMSSPREFIX$LVMPARTNAME			# name of the snapshot volume

# beginning
if [ "$#" -ne 5 ]; then
	echo "${red}Illegal number of parameters.${nocolor}"
	logger -t $LOGTAG Script failed, because of illegal number of parameters.
	logger -t $LOGTAG Hostname: $Hostname LVM partition: $LVMPARTNAME KVM guest: $GUESTNAME
	tellhow
	exit 1
fi

logger -t $LOGTAG "script begins"
logger -t $LOGTAG "backup volume $LVMVOLDEV virtual machine $GUESTNAME"

# remove yesterday's snapshot

if [ -b $LVMVOLDEV ]; then
	if [ -b $LVMSSDEV ]; then
		logger -t $LOGTAG `$LVPATH/lvremove -f $LVMSSDEV`
	else
		logger -t $LOGTAG there was no logical snapshot volume at $LVMSSDEV to remove
	fi
	# suspend kvm guest
	logger -t $LOGTAG `$VIRSHPATH/virsh suspend $GUESTNAME`
	# create today's snapshot
	logger -t $LOGTAG `$LVPATH/lvcreate --size $LVMSSSIZE -s -n $LVMSSNAME $LVMVOLDEV`
	# unpause kvm guest
	logger -t $LOGTAG `$VIRSHPATH/virsh resume $GUESTNAME`
else
	logger -t $LOGTAG $LVMVOLDEV does not exist, no action.
	exit 1
fi
#finishing
logger -t $LOGTAG "script end"
exit 0
